#!/bin/bash

# TODO LIST:
#	* Por algum motivo os ifs [[ ]] não estão funcionando, aí a rotação tbm n
#	* Add flags/options ?

[[ $# -lt 3 ]] && echo 'Usage: <PATH to backup> <PATH to save> <Backup Name>' && exit

[[ ! -d $1 ]] && echo "$1 is not a directory!" && exit
[[ ! -d $2 ]] && echo "$2 is not a directory!" && exit

now=$(date '+%Y%m%d-%H-%M-%S') &&
	tar -cf $2/$now-$3.tar $1 &&
	for file in $(ls --format=single-colum --reverse $2 | grep $3.tar); do
		[[ ${file:0:4} -lt ${now:0:4} ]] && # Check Year
			rm $file
		{
			case ${file:4:2} in # Check Month
			01|02|03|04|05|06|07|10|11|12)
				case ${now:4:2} in
				01|02|03|04|05|06|07|10|11|12)
					[[ ${file:4:2} -lt ${now:4:2} ]] &&
						rm $file ;;
				08|09)
					[[ ${file:4:2} -lt ${now:5:1} ]] &&
						rm $file ;;
				esac ;;
			08|09)
				case ${now:4:2} in
				01|02|03|04|05|06|07|10|11|12)
					[[ ${file:5:1} -lt ${now:4:2} ]] &&
						rm $file ;;
				08|09)
					[[ ${file:5:1} -lt ${now:5:1} ]] &&
						rm $file ;;
				esac ;;
			esac
		}
		{
			case ${file:6:2} in
			01|02|03|04|05|06|07|10|11|12)
				case ${now:6:2} in
				01|02|03|04|05|06|07|10|11|12)
					[[ ${file:6:2} -lt $(( ${now:6:2} - 3 )) ]] &&
						rm $file ;;
				08|09)
					[[ ${file:6:2} -lt $(( ${now:7:1} - 3)) ]] &&
						rm $file ;;
				esac ;;
			08|09)
				case ${now:6:2} in
				01|02|03|04|05|06|07|10|11|12)
					[[ ${file:7:1} -lt $(( ${now:6:2} - 3)) ]] &&
						rm $file ;;
				08|09)
					[[ ${file:7:1} -lt $(( ${now:7:1} - 3)) ]] &&
						rm $file ;;
				esac ;;
			esac
		}
	done
exit
