#!/bin/bash

# TODO LIST:
#	* Clear unecessary echos
#	* Compact generated 'tar's
#	* Add flags/options ?

[[ $# -lt 3 ]] && echo 'Usage: <PATH to backup> <PATH to save> <Backup Name>' && exit

echo "Printing Argument List:"
for i in $@; do {
	echo -n "$i "
	lastarg=$i
}
done
echo
echo backupname: $lastarg

[[ ! -d $1 ]] && echo "$1 is not a directory!" && exit
[[ ! -d $2 ]] && echo "$2 is not a directory!" && exit

now=$(date '+%Y%m%d-%H-%M-%S') &&
	#tar -cf $2/$now-$3.tar $1 &&
	for file in $(ls --format=single-colum --reverse $2 | grep $3.tar); do
		echo ---$file
		[[ ${file:0:4} -lt ${now:0:4} ]] &&
			echo "YEAR: \"${file:0:4} < ${now:0:4}\": rm $file" ||
		{
			case ${file:4:2} in
			01|02|03|04|05|06|07|10|11|12)
				case ${now:4:2} in
				01|02|03|04|05|06|07|10|11|12)
					[[ ${file:4:2} -lt ${now:4:2} ]] &&
						echo "MONTH: \"${file:4:2} < ${now:4:2}\": rm $file" ;;
				08|09)
					[[ ${file:4:2} -lt ${now:5:1} ]] &&
						echo "MONTH: \"${file:4:2} < ${now:4:2}\": rm $file" ;;
				esac ;;
			08|09)
				case ${now:4:2} in
				01|02|03|04|05|06|07|10|11|12)
					[[ ${file:5:1} -lt ${now:4:2} ]] &&
						echo "MONTH: \"${file:4:2} < ${now:4:2}\": rm $file" ;;
				08|09)
					[[ ${file:5:1} -lt ${now:5:1} ]] &&
						echo "MONTH: \"${file:4:2} < ${now:4:2}\": rm $file" ;;
				esac ;;
			esac
		} ||
		{
			case ${file:6:2} in
			01|02|03|04|05|06|07|10|11|12)
				case ${now:6:2} in
				01|02|03|04|05|06|07|10|11|12)
					[[ ${file:6:2} -lt ${now:6:2} ]] &&
						echo "DAY: \"${file} < ${now}\": rm $file" ;;
				08|09)
					[[ ${file:6:2} -lt ${now:7:1} ]] &&
						echo "DAY: \"${file} < ${now}\": rm $file" ;;
				esac ;;
			08|09)
				case ${now:6:2} in
				01|02|03|04|05|06|07|10|11|12)
					[[ ${file:7:1} -lt ${now:6:2} ]] &&
						echo "DAY: \"${file} < ${now}\": rm $file" ;;
				08|09)
					[[ ${file:7:1} -lt $(( ${now:7:1} - 3)) ]] &&
						echo "DAY: \"${file} < ${now}\": rm $file" ;;
				esac ;;
			esac
		}
	done

echo "Ok"
exit
